# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-added-large-files

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
    -   id: autopep8

-   repo: https://github.com/pre-commit/mirrors-fixmyjs
    rev: v2.0.0
    hooks:
    -   id: fixmyjs
