/**
 * Fitbit Web API Explorer
 * Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/developer-guide/authorization/.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FitbitWebApiExplorer);
  }
}(this, function(expect, FitbitWebApiExplorer) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FitbitWebApiExplorer.ActivityApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ActivityApi', function() {
    describe('addActivitiesLog', function() {
      it('should call addActivitiesLog successfully', function(done) {
        //uncomment below and update the code to test addActivitiesLog
        //instance.addActivitiesLog(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addFavoriteActivities', function() {
      it('should call addFavoriteActivities successfully', function(done) {
        //uncomment below and update the code to test addFavoriteActivities
        //instance.addFavoriteActivities(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addUpdateActivitiesGoals', function() {
      it('should call addUpdateActivitiesGoals successfully', function(done) {
        //uncomment below and update the code to test addUpdateActivitiesGoals
        //instance.addUpdateActivitiesGoals(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteActivitiesLog', function() {
      it('should call deleteActivitiesLog successfully', function(done) {
        //uncomment below and update the code to test deleteActivitiesLog
        //instance.deleteActivitiesLog(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteFavoriteActivities', function() {
      it('should call deleteFavoriteActivities successfully', function(done) {
        //uncomment below and update the code to test deleteFavoriteActivities
        //instance.deleteFavoriteActivities(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getActivitiesByDate', function() {
      it('should call getActivitiesByDate successfully', function(done) {
        //uncomment below and update the code to test getActivitiesByDate
        //instance.getActivitiesByDate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getActivitiesGoals', function() {
      it('should call getActivitiesGoals successfully', function(done) {
        //uncomment below and update the code to test getActivitiesGoals
        //instance.getActivitiesGoals(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getActivitiesLog', function() {
      it('should call getActivitiesLog successfully', function(done) {
        //uncomment below and update the code to test getActivitiesLog
        //instance.getActivitiesLog(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getActivitiesLogList', function() {
      it('should call getActivitiesLogList successfully', function(done) {
        //uncomment below and update the code to test getActivitiesLogList
        //instance.getActivitiesLogList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getActivitiesTCX', function() {
      it('should call getActivitiesTCX successfully', function(done) {
        //uncomment below and update the code to test getActivitiesTCX
        //instance.getActivitiesTCX(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getActivitiesTypeDetail', function() {
      it('should call getActivitiesTypeDetail successfully', function(done) {
        //uncomment below and update the code to test getActivitiesTypeDetail
        //instance.getActivitiesTypeDetail(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getActivitiesTypes', function() {
      it('should call getActivitiesTypes successfully', function(done) {
        //uncomment below and update the code to test getActivitiesTypes
        //instance.getActivitiesTypes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFavoriteActivities', function() {
      it('should call getFavoriteActivities successfully', function(done) {
        //uncomment below and update the code to test getFavoriteActivities
        //instance.getFavoriteActivities(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFrequentActivities', function() {
      it('should call getFrequentActivities successfully', function(done) {
        //uncomment below and update the code to test getFrequentActivities
        //instance.getFrequentActivities(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getRecentActivities', function() {
      it('should call getRecentActivities successfully', function(done) {
        //uncomment below and update the code to test getRecentActivities
        //instance.getRecentActivities(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
