/**
 * Fitbit Web API Explorer
 * Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/developer-guide/authorization/.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";

/**
* ActiveZoneMinutesTimeSeries service.
* @module api/ActiveZoneMinutesTimeSeriesApi
* @version 1
*/
export default class ActiveZoneMinutesTimeSeriesApi {

    /**
    * Constructs a new ActiveZoneMinutesTimeSeriesApi. 
    * @alias module:api/ActiveZoneMinutesTimeSeriesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getAZMTimeSeriesByDate operation.
     * @callback module:api/ActiveZoneMinutesTimeSeriesApi~getAZMTimeSeriesByDateCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get AZM Time Series by Date
     * Returns the daily summary values over a period of time by specifying a date and time period.
     * @param {Date} date The date in the format yyyy-MM-dd or today
     * @param {module:model/String} period The range for which data will be returned. **Supported:** 1d | 7d | 30d | 1w | 1m | 3m | 6m | 1y
     * @param {module:api/ActiveZoneMinutesTimeSeriesApi~getAZMTimeSeriesByDateCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getAZMTimeSeriesByDate(date, period, callback) {
      let postBody = null;
      // verify the required parameter 'date' is set
      if (date === undefined || date === null) {
        throw new Error("Missing the required parameter 'date' when calling getAZMTimeSeriesByDate");
      }
      // verify the required parameter 'period' is set
      if (period === undefined || period === null) {
        throw new Error("Missing the required parameter 'period' when calling getAZMTimeSeriesByDate");
      }

      let pathParams = {
        'date': date,
        'period': period
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/1/user/-/activities/active-zone-minutes/date/{date}/{period}.json', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAZMTimeSeriesByInterval operation.
     * @callback module:api/ActiveZoneMinutesTimeSeriesApi~getAZMTimeSeriesByIntervalCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get AZM Time Series by Interval
     * Returns the daily summary values over an interval by specifying a date range.
     * @param {Date} startDate The date in the format yyyy-MM-dd or today
     * @param {Date} endDate The date in the format yyyy-MM-dd or today
     * @param {module:api/ActiveZoneMinutesTimeSeriesApi~getAZMTimeSeriesByIntervalCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getAZMTimeSeriesByInterval(startDate, endDate, callback) {
      let postBody = null;
      // verify the required parameter 'startDate' is set
      if (startDate === undefined || startDate === null) {
        throw new Error("Missing the required parameter 'startDate' when calling getAZMTimeSeriesByInterval");
      }
      // verify the required parameter 'endDate' is set
      if (endDate === undefined || endDate === null) {
        throw new Error("Missing the required parameter 'endDate' when calling getAZMTimeSeriesByInterval");
      }

      let pathParams = {
        'start-date': startDate,
        'end-date': endDate
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/1/user/-/activities/active-zone-minutes/date/{start-date}/{end-date}.json', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
