/**
 * Fitbit Web API Explorer
 * Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/developer-guide/authorization/.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";

/**
* ActiveZoneMinutesIntradayTimeSeries service.
* @module api/ActiveZoneMinutesIntradayTimeSeriesApi
* @version 1
*/
export default class ActiveZoneMinutesIntradayTimeSeriesApi {

    /**
    * Constructs a new ActiveZoneMinutesIntradayTimeSeriesApi. 
    * @alias module:api/ActiveZoneMinutesIntradayTimeSeriesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getAZMByDateIntraday operation.
     * @callback module:api/ActiveZoneMinutesIntradayTimeSeriesApi~getAZMByDateIntradayCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get AZM Intraday by Date
     * Returns the active zone minutes intraday data for a 24 hour period by specifying a date and/or time range.
     * @param {Date} date The date in the format yyyy-MM-dd or today
     * @param {module:model/String} detailLevel The detail for which data will be returned. **Supported:** 1min | 5min | 15min
     * @param {module:api/ActiveZoneMinutesIntradayTimeSeriesApi~getAZMByDateIntradayCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getAZMByDateIntraday(date, detailLevel, callback) {
      let postBody = null;
      // verify the required parameter 'date' is set
      if (date === undefined || date === null) {
        throw new Error("Missing the required parameter 'date' when calling getAZMByDateIntraday");
      }
      // verify the required parameter 'detailLevel' is set
      if (detailLevel === undefined || detailLevel === null) {
        throw new Error("Missing the required parameter 'detailLevel' when calling getAZMByDateIntraday");
      }

      let pathParams = {
        'date': date,
        'detail-level': detailLevel
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/1/user/-/activities/active-zone-minutes/date/{date}/1d/{detail-level}.json', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAZMByDateTimeSeriesIntraday operation.
     * @callback module:api/ActiveZoneMinutesIntradayTimeSeriesApi~getAZMByDateTimeSeriesIntradayCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get AZM Intraday by Date
     * Returns the active zone minutes intraday data for a 24 hour period by specifying a date and/or time range.
     * @param {Date} date The date in the format yyyy-MM-dd or today
     * @param {module:model/String} detailLevel The detail for which data will be returned. **Supported:** 1min | 5min | 15min
     * @param {String} startTime The start of the period in the format HH:mm.
     * @param {String} endTime The end of the period in the format HH:mm.
     * @param {module:api/ActiveZoneMinutesIntradayTimeSeriesApi~getAZMByDateTimeSeriesIntradayCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getAZMByDateTimeSeriesIntraday(date, detailLevel, startTime, endTime, callback) {
      let postBody = null;
      // verify the required parameter 'date' is set
      if (date === undefined || date === null) {
        throw new Error("Missing the required parameter 'date' when calling getAZMByDateTimeSeriesIntraday");
      }
      // verify the required parameter 'detailLevel' is set
      if (detailLevel === undefined || detailLevel === null) {
        throw new Error("Missing the required parameter 'detailLevel' when calling getAZMByDateTimeSeriesIntraday");
      }
      // verify the required parameter 'startTime' is set
      if (startTime === undefined || startTime === null) {
        throw new Error("Missing the required parameter 'startTime' when calling getAZMByDateTimeSeriesIntraday");
      }
      // verify the required parameter 'endTime' is set
      if (endTime === undefined || endTime === null) {
        throw new Error("Missing the required parameter 'endTime' when calling getAZMByDateTimeSeriesIntraday");
      }

      let pathParams = {
        'date': date,
        'detail-level': detailLevel,
        'start-time': startTime,
        'end-time': endTime
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/1/user/-/activities/active-zone-minutes/date/{date}/1d/{detail-level}/time/{start-time}/{end-time}.json', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAZMByIntervalIntraday operation.
     * @callback module:api/ActiveZoneMinutesIntradayTimeSeriesApi~getAZMByIntervalIntradayCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get AZM Intraday by Interval
     * Returns the active zone minutes intraday data for a 24 hour period by specifying a date range and/or time range.
     * @param {Date} startDate The date in the format yyyy-MM-dd or today
     * @param {Date} endDate The date in the format yyyy-MM-dd or today
     * @param {module:model/String} detailLevel The detail for which data will be returned. **Support:** 1min | 5min | 15min
     * @param {module:api/ActiveZoneMinutesIntradayTimeSeriesApi~getAZMByIntervalIntradayCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getAZMByIntervalIntraday(startDate, endDate, detailLevel, callback) {
      let postBody = null;
      // verify the required parameter 'startDate' is set
      if (startDate === undefined || startDate === null) {
        throw new Error("Missing the required parameter 'startDate' when calling getAZMByIntervalIntraday");
      }
      // verify the required parameter 'endDate' is set
      if (endDate === undefined || endDate === null) {
        throw new Error("Missing the required parameter 'endDate' when calling getAZMByIntervalIntraday");
      }
      // verify the required parameter 'detailLevel' is set
      if (detailLevel === undefined || detailLevel === null) {
        throw new Error("Missing the required parameter 'detailLevel' when calling getAZMByIntervalIntraday");
      }

      let pathParams = {
        'start-date': startDate,
        'end-date': endDate,
        'detail-level': detailLevel
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/1/user/-/activities/active-zone-minutes/date/{start-date}/{end-date}/{detail-level}.json', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAZMByIntervalTimeSeriesIntraday operation.
     * @callback module:api/ActiveZoneMinutesIntradayTimeSeriesApi~getAZMByIntervalTimeSeriesIntradayCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get AZM Intraday by Interval
     * Returns the active zone minutes intraday data for a 24 hour period by specifying a date range and/or time range.
     * @param {Date} startDate The date in the format yyyy-MM-dd or today
     * @param {Date} endDate The date in the format yyyy-MM-dd or today
     * @param {module:model/String} detailLevel The detail for which data will be returned. **Support:** 1min | 5min | 15min
     * @param {String} startTime The start of the period in the format HH:mm.
     * @param {String} endTime The end of the period in the format HH:mm.
     * @param {module:api/ActiveZoneMinutesIntradayTimeSeriesApi~getAZMByIntervalTimeSeriesIntradayCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getAZMByIntervalTimeSeriesIntraday(startDate, endDate, detailLevel, startTime, endTime, callback) {
      let postBody = null;
      // verify the required parameter 'startDate' is set
      if (startDate === undefined || startDate === null) {
        throw new Error("Missing the required parameter 'startDate' when calling getAZMByIntervalTimeSeriesIntraday");
      }
      // verify the required parameter 'endDate' is set
      if (endDate === undefined || endDate === null) {
        throw new Error("Missing the required parameter 'endDate' when calling getAZMByIntervalTimeSeriesIntraday");
      }
      // verify the required parameter 'detailLevel' is set
      if (detailLevel === undefined || detailLevel === null) {
        throw new Error("Missing the required parameter 'detailLevel' when calling getAZMByIntervalTimeSeriesIntraday");
      }
      // verify the required parameter 'startTime' is set
      if (startTime === undefined || startTime === null) {
        throw new Error("Missing the required parameter 'startTime' when calling getAZMByIntervalTimeSeriesIntraday");
      }
      // verify the required parameter 'endTime' is set
      if (endTime === undefined || endTime === null) {
        throw new Error("Missing the required parameter 'endTime' when calling getAZMByIntervalTimeSeriesIntraday");
      }

      let pathParams = {
        'start-date': startDate,
        'end-date': endDate,
        'detail-level': detailLevel,
        'start-time': startTime,
        'end-time': endTime
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/1/user/-/activities/active-zone-minutes/date/{start-date}/{end-date}/time/{start-time}/{end-time}.json', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
